const KEY='hanbaiKanriV1';
const IDB_NAME='hanbaiKanriDatabase',IDB_STORE='data';
const blank={company:{name:'',postal:'',address:'',tel:'',invoiceNo:'',bank:'',note:''},customers:[],products:[],documents:[],payments:[],sequence:1};
let db=load(), page='dashboard', editing=null;
function load(){try{return {...structuredClone(blank),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(blank)}}
function openDataDB(){return new Promise((resolve,reject)=>{let q=indexedDB.open(IDB_NAME,1);q.onupgradeneeded=()=>q.result.createObjectStore(IDB_STORE);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
async function idbRead(key='current'){try{let x=await openDataDB();return await new Promise((resolve,reject)=>{let q=x.transaction(IDB_STORE).objectStore(IDB_STORE).get(key);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}catch{return null}}
async function idbWrite(value){try{let x=await openDataDB(),old=await idbRead('current');await new Promise((resolve,reject)=>{let tx=x.transaction(IDB_STORE,'readwrite'),s=tx.objectStore(IDB_STORE);if(old)s.put(old,'backup');s.put(structuredClone(value),'current');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});return true}catch(e){console.error('IndexedDB save failed',e);return false}}
let saveQueue=Promise.resolve();
function save(){db._savedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(db))}catch(e){console.warn('localStorage capacity exceeded; using IndexedDB',e)}let snapshot=structuredClone(db);saveQueue=saveQueue.then(()=>idbWrite(snapshot));return saveQueue}
async function init(){let stored=await idbRead('current'),local=db;if(stored){let st=stored._savedAt||'',lt=local._savedAt||'';if(st>=lt||(!local.documents.length&&stored.documents?.length))db={...structuredClone(blank),...stored}}else if(local.customers.length||local.products.length||local.documents.length)await idbWrite(local);render()}
const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Number(n)||0);
const today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const id=()=>crypto.randomUUID?.()||Date.now()+Math.random().toString(16).slice(2);
function toast(s){const x=document.querySelector('#toast');x.textContent=s;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function setPage(p){page=p;editing=null;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));render()}
document.querySelector('#nav').onclick=e=>e.target.dataset.page&&setPage(e.target.dataset.page);
document.querySelector('#quick-new').onclick=()=>setPage('editor');
function title(s){document.querySelector('#page-title').textContent=s}
function render(){if(page.startsWith('doc-'))return documentTypePage(page.slice(4));({dashboard:dashboard,documents:documents,editor:editor,customers:customers,products:products,payments:payments,migration:migration,settings:settings}[page]||dashboard)()}
function dashboard(){title('ホーム');const sales=db.documents.filter(d=>['納品書','請求書'].includes(d.type));const thisMonth=today().slice(0,7);const monthly=sales.filter(d=>d.date?.startsWith(thisMonth)).reduce((a,d)=>a+d.total,0);const paid=db.payments.reduce((a,p)=>a+Number(p.amount),0);const billed=db.documents.filter(d=>d.type==='請求書').reduce((a,d)=>a+d.total,0);document.querySelector('#app').innerHTML=`
 <div class="grid stats"><div class="card"><div class="stat-label">今月の売上</div><div class="stat-value">${yen(monthly)}</div></div><div class="card"><div class="stat-label">請求総額</div><div class="stat-value">${yen(billed)}</div></div><div class="card"><div class="stat-label">売掛残高</div><div class="stat-value">${yen(Math.max(0,billed-paid))}</div></div><div class="card"><div class="stat-label">得意先数</div><div class="stat-value">${db.customers.length} 件</div></div></div>
 <div class="grid two-col"><div class="card"><h2>最近の伝票</h2>${docTable(db.documents.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6),false)}</div><div class="card"><h2>はじめに</h2><p class="hint">① 自社設定を登録<br>② 「販売ラクダから移行」で既存CSVを読み込む<br>③ 伝票を作成し、印刷画面からPDF保存<br>④ 定期的にバックアップを書き出してください。</p></div></div>`}
function docTable(rows,actions=true){if(!rows.length)return '<div class="empty">伝票はまだありません</div>';return `<table><thead><tr><th>日付</th><th>番号</th><th>種類</th><th>得意先</th><th class="num">金額</th>${actions?'<th></th>':''}</tr></thead><tbody>${rows.map(d=>`<tr><td>${esc(d.date)}</td><td>${esc(d.number)}</td><td>${esc(d.type)}</td><td>${esc(d.customerName)}</td><td class="num">${yen(d.total)}</td>${actions?`<td class="table-actions"><button onclick="editDoc('${d.id}')">編集</button><button onclick="copyDoc('${d.id}')">転記</button><button onclick="printDoc('${d.id}')">印刷</button><button onclick="removeDoc('${d.id}')">削除</button></td>`:''}</tr>`).join('')}</tbody></table>`}
function jpDate(s){if(!s)return '日付なし';let [y,m,d]=s.split('-');return `${y}年${m}月${d}日`}
function groupedDocTable(rows){if(!rows.length)return '<div class="empty">伝票はまだありません</div>';let sorted=[...rows].sort((a,b)=>(b.date||'').localeCompare(a.date||'')||(b.number||'').localeCompare(a.number||'')),groups=new Map();sorted.forEach(d=>{let k=d.date||'';if(!groups.has(k))groups.set(k,[]);groups.get(k).push(d)});return `<table class="grouped-docs"><thead><tr><th>伝票番号</th><th>得意先名</th><th class="num">合計金額</th><th>種類</th><th></th></tr></thead><tbody>${[...groups].map(([date,docs])=>`<tr class="date-group"><td colspan="5">${jpDate(date)} <span>${docs.length}件</span></td></tr>${docs.map(d=>`<tr><td>${esc(d.number)}</td><td>${esc(d.customerName)}</td><td class="num">${yen(d.total)}</td><td>${esc(d.type)}</td><td class="table-actions"><button onclick="editDoc('${d.id}')">開く</button><button onclick="copyDoc('${d.id}')">転記</button><button onclick="printDoc('${d.id}')">印刷</button><button onclick="removeDoc('${d.id}')">削除</button></td></tr>`).join('')}`).join('')}</tbody></table>`}
function documents(){title('伝票一覧');document.querySelector('#app').innerHTML=`<div class="toolbar"><select id="doc-filter"><option>すべて</option>${['見積書','納品書','請求書','領収書','合計請求書'].map(x=>`<option>${x}</option>`)}</select><input id="doc-search" placeholder="得意先・伝票番号で検索"><button class="primary" onclick="setPage('editor')">＋ 新規作成</button></div><div class="card" id="doc-list">${docTable(db.documents)}</div>`;const run=()=>{let a=db.documents,f=document.querySelector('#doc-filter').value,q=document.querySelector('#doc-search').value.toLowerCase();if(f!=='すべて')a=a.filter(d=>d.type===f);if(q)a=a.filter(d=>(d.customerName+d.number).toLowerCase().includes(q));document.querySelector('#doc-list').innerHTML=docTable(a)};document.querySelector('#doc-filter').onchange=run;document.querySelector('#doc-search').oninput=run}
function documentTypePage(type){title(`${type}一覧`);let rows=db.documents.filter(d=>d.type===type);document.querySelector('#app').innerHTML=`<div class="toolbar"><input id="type-search" placeholder="得意先名・伝票番号で検索"><input type="date" id="date-from" title="開始日"><span>～</span><input type="date" id="date-to" title="終了日"><button class="secondary" onclick="clearTypeFilters()">条件をクリア</button><button class="primary" onclick="newTypedDoc('${type}')">＋ ${type}を作成</button></div><div class="card" id="type-doc-list">${groupedDocTable(rows)}</div>`;window.currentDocType=type;const run=()=>{let q=document.querySelector('#type-search').value.toLowerCase(),from=document.querySelector('#date-from').value,to=document.querySelector('#date-to').value,a=db.documents.filter(d=>d.type===type);if(q)a=a.filter(d=>(d.customerName+d.number).toLowerCase().includes(q));if(from)a=a.filter(d=>(d.date||'')>=from);if(to)a=a.filter(d=>(d.date||'')<=to);document.querySelector('#type-doc-list').innerHTML=groupedDocTable(a)};document.querySelector('#type-search').oninput=run;document.querySelector('#date-from').onchange=run;document.querySelector('#date-to').onchange=run}
function clearTypeFilters(){documentTypePage(window.currentDocType)}
function newTypedDoc(type){editing={id:id(),type,date:today(),due:'',customerId:'',customerName:'',subject:'',note:'',lines:[{id:id(),code:'',name:'',qty:1,unit:'個',price:0,tax:10}],number:''};page='editor';render()}
function editor(){title(editing?'伝票を編集':'伝票を作成');const d=editing||{id:id(),type:'請求書',date:today(),due:'',customerId:'',customerName:'',subject:'',note:'',lines:[{id:id(),code:'',name:'',qty:1,unit:'個',price:0,tax:10}],number:''};document.querySelector('#app').innerHTML=`<div class="card"><div class="form-grid"><div class="field"><label>伝票種類</label><select id="d-type">${['見積書','納品書','請求書','領収書','合計請求書'].map(x=>`<option ${d.type===x?'selected':''}>${x}</option>`)}</select></div><div class="field"><label>発行日</label><input type="date" id="d-date" value="${d.date}"></div><div class="field"><label>支払期限</label><input type="date" id="d-due" value="${d.due||''}"></div><div class="field wide"><label>得意先</label><input id="d-customer" list="customer-list" value="${esc(d.customerName)}" placeholder="名称を入力・選択"><datalist id="customer-list">${db.customers.map(c=>`<option value="${esc(c.name)}">${esc(c.code||'')}</option>`)}</datalist></div><div class="field"><label>件名</label><input id="d-subject" value="${esc(d.subject||'')}"></div></div><h2 style="margin-top:25px">明細</h2><table class="line-table"><thead><tr><th>商品コード</th><th>品名・摘要</th><th>数量</th><th>単位</th><th>単価</th><th>税率</th><th class="num">金額</th><th></th></tr></thead><tbody id="lines"></tbody></table><button class="secondary no-print" style="margin-top:10px" onclick="addLine()">＋ 明細を追加</button><div class="totals" id="totals"></div><div class="field full"><label>備考</label><textarea id="d-note">${esc(d.note||'')}</textarea></div><div class="toolbar no-print" style="margin-top:20px"><button class="primary" onclick="saveDoc()">保存する</button><button class="secondary" onclick="setPage('documents')">キャンセル</button></div></div>`;editing=d;drawLines()}
function drawLines(){document.querySelector('#lines').innerHTML=editing.lines.map((l,i)=>`<tr><td><input value="${esc(l.code)}" onchange="lineChange(${i},'code',this.value)"></td><td><input class="desc" list="product-list" value="${esc(l.name)}" onchange="pickProduct(${i},this.value)">${i===0?`<datalist id="product-list">${db.products.map(p=>`<option value="${esc(p.name)}">${esc(p.code||'')}</option>`)}</datalist>`:''}</td><td><input type="number" min="0" step="0.01" value="${l.qty}" onchange="lineChange(${i},'qty',this.value)"></td><td><input value="${esc(l.unit)}" onchange="lineChange(${i},'unit',this.value)"></td><td><input type="number" value="${l.price}" onchange="lineChange(${i},'price',this.value)"></td><td><select onchange="lineChange(${i},'tax',this.value)"><option value="10" ${l.tax==10?'selected':''}>10%</option><option value="8" ${l.tax==8?'selected':''}>8%</option><option value="0" ${l.tax==0?'selected':''}>非課税</option></select></td><td class="num">${yen(l.qty*l.price)}</td><td><button class="danger" onclick="delLine(${i})">×</button></td></tr>`).join('');calc()}
function addLine(){editing.lines.push({id:id(),code:'',name:'',qty:1,unit:'個',price:0,tax:10});drawLines()}
function delLine(i){if(editing.lines.length>1)editing.lines.splice(i,1);drawLines()}
function lineChange(i,k,v){editing.lines[i][k]=['qty','price','tax'].includes(k)?Number(v):v;drawLines()}
function pickProduct(i,name){let p=db.products.find(x=>x.name===name);editing.lines[i]={...editing.lines[i],name,...(p?{code:p.code,unit:p.unit,price:Number(p.price),tax:Number(p.tax)}:{})};drawLines()}
function totals(d=editing){const sub=d.lines.reduce((a,l)=>a+l.qty*l.price,0),tax=d.lines.reduce((a,l)=>a+Math.floor(l.qty*l.price*l.tax/100),0);return{sub,tax,total:sub+tax}}
function calc(){const t=totals();document.querySelector('#totals').innerHTML=`<div><span>小計</span><span>${yen(t.sub)}</span></div><div><span>消費税</span><span>${yen(t.tax)}</span></div><div class="grand"><span>合計</span><span>${yen(t.total)}</span></div>`}
function saveDoc(){let name=document.querySelector('#d-customer').value.trim();if(!name)return alert('得意先を入力してください');Object.assign(editing,{type:document.querySelector('#d-type').value,date:document.querySelector('#d-date').value,due:document.querySelector('#d-due').value,customerName:name,customerId:db.customers.find(c=>c.name===name)?.id||'',subject:document.querySelector('#d-subject').value,note:document.querySelector('#d-note').value,...totals()});if(!editing.number)editing.number=`${{見積書:'M',納品書:'N',請求書:'S',領収書:'R',合計請求書:'G'}[editing.type]}-${String(db.sequence++).padStart(6,'0')}`;let i=db.documents.findIndex(x=>x.id===editing.id);i<0?db.documents.push(editing):db.documents[i]=editing;save();toast('伝票を保存しました');setPage('documents')}
function editDoc(x){editing=structuredClone(db.documents.find(d=>d.id===x));page='editor';render()}
function copyDoc(x){const src=db.documents.find(d=>d.id===x),to=prompt('転記先の種類を入力してください（見積書・納品書・請求書・領収書・合計請求書）','請求書');if(!['見積書','納品書','請求書','領収書','合計請求書'].includes(to))return;editing={...structuredClone(src),id:id(),type:to,date:today(),number:'',lines:src.lines.map(l=>({...l,id:id()}))};page='editor';render()}
function removeDoc(x){if(confirm('この伝票を削除しますか？')){db.documents=db.documents.filter(d=>d.id!==x);save();render()}}
function printDoc(x){const d=db.documents.find(d=>d.id===x),c=db.customers.find(c=>c.id===d.customerId)||{},co=db.company;const w=open('','_blank');w.document.write(`<!doctype html><html lang="ja"><head><meta charset="utf-8"><title>${d.type}_${d.number}</title><style>body{font-family:Meiryo,sans-serif;color:#222;margin:35px}h1{text-align:center;letter-spacing:8px;border-bottom:3px double #333;padding-bottom:12px}.top{display:flex;justify-content:space-between;margin:35px 0}.customer{font-size:18px;border-bottom:1px solid;width:48%;padding:15px 0}.company{text-align:right;font-size:12px;line-height:1.7}table{width:100%;border-collapse:collapse}th,td{border:1px solid #777;padding:8px;font-size:12px}th{background:#eee}.num{text-align:right}.total{width:42%;margin:20px 0 20px auto}.total td:first-child{background:#eee}.grand{font-size:18px;font-weight:bold}.note{border:1px solid #777;min-height:60px;padding:10px;margin-top:25px;font-size:12px}@media print{button{display:none}}</style></head><body><button onclick="print()">印刷／PDF保存</button><h1>${esc(d.type)}</h1><div class="top"><div class="customer">${esc(d.customerName)}　御中<br><small>${esc(c.postal||'')} ${esc(c.address||'')}</small></div><div class="company">${esc(co.name)}<br>${esc(co.postal)} ${esc(co.address)}<br>TEL ${esc(co.tel)}<br>${co.invoiceNo?'登録番号 '+esc(co.invoiceNo):''}</div></div><p>伝票番号：${esc(d.number)}　　発行日：${esc(d.date)}</p>${d.subject?`<p>件名：${esc(d.subject)}</p>`:''}<table><thead><tr><th>商品コード</th><th>品名・摘要</th><th>数量</th><th>単位</th><th>単価</th><th>税率</th><th>金額</th></tr></thead><tbody>${d.lines.map(l=>`<tr><td>${esc(l.code)}</td><td>${esc(l.name)}</td><td class="num">${l.qty}</td><td>${esc(l.unit)}</td><td class="num">${yen(l.price)}</td><td class="num">${l.tax}%</td><td class="num">${yen(l.qty*l.price)}</td></tr>`).join('')}</tbody></table><table class="total"><tr><td>小計</td><td class="num">${yen(d.sub)}</td></tr><tr><td>消費税</td><td class="num">${yen(d.tax)}</td></tr><tr class="grand"><td>合計</td><td class="num">${yen(d.total)}</td></tr></table>${d.due?`<p>お支払期限：${esc(d.due)}</p>`:''}${co.bank?`<p>お振込先：${esc(co.bank)}</p>`:''}<div class="note">備考：<br>${esc(d.note).replace(/\n/g,'<br>')}</div><script>onload=()=>setTimeout(()=>print(),300)<\/script></body></html>`);w.document.close()}
function masterPage(kind){let isC=kind==='customers',rows=db[kind];title(isC?'得意先台帳':'商品台帳');document.querySelector('#app').innerHTML=`<div class="toolbar"><button class="primary" onclick="masterModal('${kind}')">＋ 新規登録</button><button class="secondary" onclick="document.querySelector('#csv-${kind}').click()">CSV取込</button><input hidden type="file" accept=".csv" id="csv-${kind}" onchange="importCSV('${kind}',this.files[0])"><button class="secondary" onclick="exportCSV('${kind}')">CSV出力</button></div><div class="card">${rows.length?`<table><thead><tr>${isC?'<th>コード</th><th>名称</th><th>住所</th><th>締日</th>':'<th>コード</th><th>商品名</th><th>単位</th><th class="num">単価</th><th>税率</th>'}<th></th></tr></thead><tbody>${rows.map(r=>`<tr>${isC?`<td>${esc(r.code)}</td><td>${esc(r.name)}</td><td>${esc(r.address)}</td><td>${esc(r.closing||'')}</td>`:`<td>${esc(r.code)}</td><td>${esc(r.name)}</td><td>${esc(r.unit)}</td><td class="num">${yen(r.price)}</td><td>${r.tax}%</td>`}<td class="table-actions"><button onclick="masterModal('${kind}','${r.id}')">編集</button><button onclick="removeMaster('${kind}','${r.id}')">削除</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">データはまだありません</div>'}</div>`}
function customers(){masterPage('customers')}function products(){masterPage('products')}
function masterModal(kind,x){const isC=kind==='customers',r=db[kind].find(a=>a.id===x)||{id:id(),code:'',name:'',postal:'',address:'',tel:'',closing:'',unit:'個',price:0,tax:10};document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="master-modal"><div class="modal-box"><div class="modal-head"><h2>${isC?'得意先':'商品'}登録</h2><button class="close" onclick="this.closest('.modal').remove()">×</button></div><div class="form-grid"><div class="field"><label>コード</label><input id="m-code" value="${esc(r.code)}"></div><div class="field wide"><label>${isC?'名称':'商品名'}</label><input id="m-name" value="${esc(r.name)}"></div>${isC?`<div class="field"><label>郵便番号</label><input id="m-postal" value="${esc(r.postal)}"></div><div class="field wide"><label>住所</label><input id="m-address" value="${esc(r.address)}"></div><div class="field"><label>電話番号</label><input id="m-tel" value="${esc(r.tel)}"></div><div class="field"><label>締日</label><input id="m-closing" value="${esc(r.closing)}" placeholder="末日／20日など"></div>`:`<div class="field"><label>単位</label><input id="m-unit" value="${esc(r.unit)}"></div><div class="field"><label>標準単価（税抜）</label><input type="number" id="m-price" value="${r.price}"></div><div class="field"><label>税率</label><select id="m-tax"><option value="10" ${r.tax==10?'selected':''}>10%</option><option value="8" ${r.tax==8?'selected':''}>8%</option><option value="0" ${r.tax==0?'selected':''}>非課税</option></select></div>`}</div><button class="primary" style="margin-top:20px" onclick="saveMaster('${kind}','${r.id}')">保存</button></div></div>`)}
function saveMaster(kind,x){let r={id:x,code:document.querySelector('#m-code').value,name:document.querySelector('#m-name').value};if(!r.name)return alert('名称を入力してください');if(kind==='customers')Object.assign(r,{postal:document.querySelector('#m-postal').value,address:document.querySelector('#m-address').value,tel:document.querySelector('#m-tel').value,closing:document.querySelector('#m-closing').value});else Object.assign(r,{unit:document.querySelector('#m-unit').value,price:Number(document.querySelector('#m-price').value),tax:Number(document.querySelector('#m-tax').value)});let i=db[kind].findIndex(a=>a.id===x);i<0?db[kind].push(r):db[kind][i]=r;save();document.querySelector('#master-modal').remove();render()}
function removeMaster(k,x){if(confirm('削除しますか？')){db[k]=db[k].filter(a=>a.id!==x);save();render()}}
function parseCSV(s){let out=[],row=[],v='',q=false;for(let i=0;i<s.length;i++){let c=s[i],n=s[i+1];if(c==='"'&&q&&n==='"'){v+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(v);v=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(v);if(row.some(x=>x.trim()))out.push(row);row=[];v=''}else v+=c}row.push(v);if(row.some(x=>x.trim()))out.push(row);return out}
function importCSV(kind,file){if(!file)return;const fr=new FileReader();fr.onload=()=>{let a=parseCSV(fr.result),h=a.shift().map(x=>x.trim());let map=kind==='customers'?{code:['コード','得意先コード'],name:['名称','得意先名','会社名'],postal:['郵便番号'],address:['住所'],tel:['電話番号','TEL'],closing:['締日']}:{code:['コード','商品コード'],name:['商品名','品名','名称'],unit:['単位'],price:['単価','標準単価'],tax:['税率']};a.forEach(row=>{let r={id:id()};for(let [k,names] of Object.entries(map)){let i=h.findIndex(x=>names.includes(x));r[k]=i>=0?row[i]:''}if(r.name){if(kind==='products'){r.price=Number(String(r.price).replace(/[,￥¥]/g,''))||0;r.tax=Number(String(r.tax).replace('%',''))||10}db[kind].push(r)}});save();toast(`${a.length}件を読み込みました`);render()};fr.readAsText(file,'UTF-8')}
function exportCSV(kind){let isC=kind==='customers',head=isC?['得意先コード','得意先名','郵便番号','住所','電話番号','締日']:['商品コード','商品名','単位','標準単価','税率'];let keys=isC?['code','name','postal','address','tel','closing']:['code','name','unit','price','tax'];let s='\uFEFF'+[head,...db[kind].map(r=>keys.map(k=>r[k]??''))].map(row=>row.map(x=>`"${String(x).replace(/"/g,'""')}"`).join(',')).join('\r\n');download(`${kind}.csv`,s,'text/csv')}
function payments(){title('入金・売掛管理');const billed=db.documents.filter(d=>d.type==='請求書').reduce((a,d)=>a+d.total,0),paid=db.payments.reduce((a,p)=>a+Number(p.amount),0);document.querySelector('#app').innerHTML=`<div class="grid stats" style="grid-template-columns:repeat(3,1fr)"><div class="card"><div class="stat-label">請求総額</div><div class="stat-value">${yen(billed)}</div></div><div class="card"><div class="stat-label">入金総額</div><div class="stat-value">${yen(paid)}</div></div><div class="card"><div class="stat-label">売掛残高</div><div class="stat-value">${yen(billed-paid)}</div></div></div><div class="toolbar" style="margin-top:20px"><button class="primary" onclick="paymentModal()">＋ 入金登録</button></div><div class="card">${db.payments.length?`<table><thead><tr><th>入金日</th><th>得意先</th><th>方法</th><th class="num">金額</th><th>備考</th><th></th></tr></thead><tbody>${db.payments.map(p=>`<tr><td>${p.date}</td><td>${esc(p.customerName)}</td><td>${esc(p.method)}</td><td class="num">${yen(p.amount)}</td><td>${esc(p.note)}</td><td><button class="danger" onclick="removePayment('${p.id}')">削除</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">入金データはありません</div>'}</div>`}
function paymentModal(){document.body.insertAdjacentHTML('beforeend',`<div class="modal"><div class="modal-box"><div class="modal-head"><h2>入金登録</h2><button class="close" onclick="this.closest('.modal').remove()">×</button></div><div class="form-grid"><div class="field"><label>入金日</label><input type="date" id="p-date" value="${today()}"></div><div class="field wide"><label>得意先</label><input id="p-customer" list="p-list"><datalist id="p-list">${db.customers.map(c=>`<option value="${esc(c.name)}">`)}</datalist></div><div class="field"><label>金額</label><input type="number" id="p-amount"></div><div class="field"><label>方法</label><select id="p-method"><option>振込</option><option>現金</option><option>口座振替</option><option>その他</option></select></div><div class="field wide"><label>備考</label><input id="p-note"></div></div><button class="primary" style="margin-top:20px" onclick="savePayment()">保存</button></div></div>`)}
function savePayment(){let p={id:id(),date:document.querySelector('#p-date').value,customerName:document.querySelector('#p-customer').value,amount:Number(document.querySelector('#p-amount').value),method:document.querySelector('#p-method').value,note:document.querySelector('#p-note').value};if(!p.customerName||!p.amount)return alert('得意先と金額を入力してください');db.payments.push(p);save();document.querySelector('.modal').remove();render()}
function removePayment(x){if(confirm('削除しますか？')){db.payments=db.payments.filter(p=>p.id!==x);save();render()}}
let migrationData=null;
const importDefs={
 customers:{label:'得意先台帳',fields:[['code','得意先コード'],['name','得意先名（必須）'],['postal','郵便番号'],['address','住所'],['tel','電話番号'],['closing','締日']]},
 products:{label:'商品台帳',fields:[['code','商品コード'],['name','商品名（必須）'],['unit','単位'],['price','標準単価'],['tax','税率']]},
 見積書:{label:'見積書',document:true},納品書:{label:'納品書',document:true},請求書:{label:'請求書',document:true},領収書:{label:'領収書',document:true},合計請求書:{label:'合計請求書',document:true}
};
const docImportFields=[['number','伝票番号'],['date','発行日'],['customerCode','得意先コード'],['customerName','得意先名（必須）'],['subject','件名'],['itemCode','商品コード'],['itemName','品名・摘要'],['qty','数量'],['unit','単位'],['price','単価'],['tax','税率'],['sub','小計'],['taxAmount','消費税額'],['total','合計金額'],['due','支払期限'],['note','備考']];
const importAliases={
 code:['コード','得意先コード','顧客コード','取引先コード'],name:['名称','得意先名','顧客名','取引先名','会社名','商品名','品名'],postal:['郵便番号','〒'],address:['住所','所在地'],tel:['電話番号','tel','電話'],closing:['締日','締め日','請求締日'],unit:['単位'],price:['標準単価','販売単価','単価','売価'],tax:['税率','消費税率'],
 number:['伝票番号','伝票no','伝票№','no','番号','見積番号','納品番号','請求番号','領収番号'],date:['発行日','伝票日付','日付','見積日','納品日','請求日','領収日'],customerCode:['得意先コード','顧客コード','取引先コード'],customerName:['得意先名','顧客名','取引先名','会社名','宛名'],subject:['件名','摘要','タイトル'],itemCode:['商品コード','品番','型番'],itemName:['商品名','品名','明細名','明細摘要','内容'],qty:['数量','数'],sub:['小計','税抜金額','本体価格'],taxAmount:['消費税額','税額'],total:['合計金額','税込金額','請求金額','領収金額','今回請求額'],due:['支払期限','お支払期限','入金期日'],note:['備考','メモ','摘要欄']
};
function migration(){title('販売ラクダから移行');migrationData=null;document.querySelector('#app').innerHTML=`<div class="notice">販売ラクダPro25から書き出したCSVを、種類ごとに読み込みます。元データと現在のデータは削除されません。同じ種類・伝票番号が既にある場合は、読み込んだ内容で更新します。</div><div class="card"><h2>1．読み込むデータを選択</h2><div class="form-grid"><div class="field"><label>データの種類</label><select id="mig-type">${Object.entries(importDefs).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('')}</select></div><div class="field wide"><label>販売ラクダから書き出したCSV</label><input type="file" id="mig-file" accept=".csv,.txt"></div></div><button class="primary" style="margin-top:18px" onclick="readMigrationFile()">CSVを読み込む</button><p class="hint">文字コードはUTF-8とShift-JISの両方に対応しています。CSVの1行目には項目名が必要です。</p></div><div id="mig-work"></div>`}
function normHeader(s){return String(s||'').trim().toLowerCase().replace(/[\s　_\-・:：\/\\()（）「」]/g,'')}
function autoHeader(headers,key){let aliases=(importAliases[key]||[]).map(normHeader),idx=headers.findIndex(h=>aliases.includes(normHeader(h)));return idx}
async function readMigrationFile(){let file=document.querySelector('#mig-file').files[0],type=document.querySelector('#mig-type').value;if(!file)return alert('CSVファイルを選択してください');let buf=await file.arrayBuffer(),textValue;try{textValue=new TextDecoder('utf-8',{fatal:true}).decode(buf)}catch{textValue=new TextDecoder('shift_jis').decode(buf)}let rows=parseCSV(textValue.replace(/^\uFEFF/,''));if(rows.length<2)return alert('CSV内にデータが見つかりません');let headers=rows.shift().map(x=>x.trim()),def=importDefs[type],fields=def.document?docImportFields:def.fields;migrationData={type,headers,rows};let options=(selected)=>`<option value="">読み込まない</option>${headers.map((h,i)=>`<option value="${i}" ${i===selected?'selected':''}>${esc(h||`列${i+1}`)}</option>`).join('')}`;document.querySelector('#mig-work').innerHTML=`<div class="card" style="margin-top:20px"><h2>2．項目の割り当て</h2><p class="hint">自動で項目を選びました。違うところだけ変更してください。</p><div class="form-grid">${fields.map(([k,label])=>`<div class="field"><label>${label}</label><select class="mig-map" data-key="${k}">${options(autoHeader(headers,k))}</select></div>`).join('')}</div><h2 style="margin-top:25px">先頭3行の確認</h2><div style="overflow:auto"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,3).map(r=>`<tr>${headers.map((_,i)=>`<td>${esc(r[i]||'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="toolbar" style="margin-top:20px"><button class="primary" onclick="runMigration()">インポートを実行</button><button class="secondary" onclick="migration()">やり直す</button></div></div>`}
function mappedRow(row,map){let o={};for(let [k,i] of Object.entries(map))o[k]=i===''?'':(row[Number(i)]??'');return o}
function cleanNum(v){let s=String(v??'').replace(/[￥¥,，円\s]/g,'').replace(/[▲△]/g,'-');let n=Number(s);return Number.isFinite(n)?n:0}
function cleanTax(v){let n=cleanNum(String(v??'').replace('%',''));return [0,8,10].includes(n)?n:10}
function cleanDate(v){let s=String(v??'').trim();if(!s)return '';let m=s.match(/(\d{4})\D+(\d{1,2})\D+(\d{1,2})/);if(m)return `${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;let serial=Number(s);if(serial>20000&&serial<80000){let d=new Date(Date.UTC(1899,11,30)+serial*86400000);return d.toISOString().slice(0,10)}return s}
async function runMigration(){if(!migrationData)return;let map={};document.querySelectorAll('.mig-map').forEach(x=>map[x.dataset.key]=x.value);let {type,rows}=migrationData;if((type==='customers'||type==='products')&&map.name==='')return alert('名称の列を選択してください');if(importDefs[type].document&&map.customerName==='')return alert('得意先名の列を選択してください');let count=0,skipped=0;
 if(type==='customers'||type==='products'){for(let row of rows){let x=mappedRow(row,map),name=String(x.name||'').trim();if(!name){skipped++;continue}let item={id:id(),code:String(x.code||'').trim(),name};if(type==='customers')Object.assign(item,{postal:x.postal||'',address:x.address||'',tel:x.tel||'',closing:x.closing||''});else Object.assign(item,{unit:x.unit||'個',price:cleanNum(x.price),tax:cleanTax(x.tax)});let at=db[type].findIndex(a=>(item.code&&a.code===item.code)||a.name===item.name);if(at>=0){item.id=db[type][at].id;db[type][at]=item}else db[type].push(item);count++}}
 else {let groups=new Map();rows.forEach((row,i)=>{let x=mappedRow(row,map),name=String(x.customerName||'').trim();if(!name){skipped++;return}let no=String(x.number||'').trim()||`移行-${type}-${i+1}`;if(!groups.has(no))groups.set(no,[]);groups.get(no).push(x)});for(let [no,a] of groups){let h=a[0],lines=a.filter(x=>x.itemName||x.itemCode||x.price||x.qty).map(x=>({id:id(),code:x.itemCode||'',name:x.itemName||'',qty:cleanNum(x.qty)||1,unit:x.unit||'個',price:cleanNum(x.price),tax:cleanTax(x.tax)}));if(!lines.length){let importedTotal=cleanNum(h.total);lines=[{id:id(),code:'',name:type==='合計請求書'?'合計請求額':'移行データ',qty:1,unit:'式',price:importedTotal,tax:0}]}let calcSub=lines.reduce((n,l)=>n+l.qty*l.price,0),calcTax=lines.reduce((n,l)=>n+Math.floor(l.qty*l.price*l.tax/100),0),customer=db.customers.find(c=>(h.customerCode&&c.code===h.customerCode)||c.name===h.customerName),doc={id:id(),type,number:no,date:cleanDate(h.date)||today(),due:cleanDate(h.due),customerId:customer?.id||'',customerName:h.customerName,subject:h.subject||'',note:h.note||'',lines,sub:h.sub!==''?cleanNum(h.sub):calcSub,tax:h.taxAmount!==''?cleanNum(h.taxAmount):calcTax,total:h.total!==''?cleanNum(h.total):calcSub+calcTax};let at=db.documents.findIndex(d=>d.type===type&&d.number===no);if(at>=0){doc.id=db.documents[at].id;db.documents[at]=doc}else db.documents.push(doc);count++}}
 let stored=await save();if(!stored)return alert('データの保存に失敗しました。CSVは閉じずにもう一度お試しください。');document.querySelector('#mig-work').innerHTML=`<div class="card" style="margin-top:20px"><h2>インポート・保存完了</h2><p><strong>${count}件</strong>を安全に保存しました。${skipped?` 得意先名・名称が空の${skipped}行は除外しました。`:''}</p><div class="toolbar"><button class="primary" onclick="setPage('${type==='customers'?'customers':type==='products'?'products':'documents'}')">読み込んだデータを確認</button><button class="secondary" onclick="migration()">別のCSVを読み込む</button></div></div>`;toast(`${count}件を保存しました`)}
function settings(){title('自社設定・バックアップ');let c=db.company;document.querySelector('#app').innerHTML=`<div class="notice">この初期版のデータは、このブラウザ内に保存されます。別のパソコンには自動共有されません。必ず定期的にバックアップしてください。</div><div class="card"><h2>自社情報</h2><div class="form-grid"><div class="field wide"><label>会社名</label><input id="s-name" value="${esc(c.name)}"></div><div class="field"><label>郵便番号</label><input id="s-postal" value="${esc(c.postal)}"></div><div class="field wide"><label>住所</label><input id="s-address" value="${esc(c.address)}"></div><div class="field"><label>電話番号</label><input id="s-tel" value="${esc(c.tel)}"></div><div class="field"><label>適格請求書発行事業者 登録番号</label><input id="s-invoice" value="${esc(c.invoiceNo)}" placeholder="T1234567890123"></div><div class="field wide"><label>振込先</label><input id="s-bank" value="${esc(c.bank)}"></div><div class="field full"><label>共通備考</label><textarea id="s-note">${esc(c.note)}</textarea></div></div><button class="primary" style="margin-top:15px" onclick="saveSettings()">設定を保存</button></div><div class="card" style="margin-top:20px"><h2>データ管理</h2><div class="toolbar"><button class="secondary" onclick="backup()">バックアップを書き出す</button><button class="secondary" onclick="document.querySelector('#restore').click()">バックアップを復元</button><input hidden type="file" accept=".json" id="restore" onchange="restore(this.files[0])"></div><p class="hint">バックアップには、自社情報・台帳・伝票・入金データがすべて含まれます。</p></div>`}
function saveSettings(){db.company={name:document.querySelector('#s-name').value,postal:document.querySelector('#s-postal').value,address:document.querySelector('#s-address').value,tel:document.querySelector('#s-tel').value,invoiceNo:document.querySelector('#s-invoice').value,bank:document.querySelector('#s-bank').value,note:document.querySelector('#s-note').value};save();toast('自社設定を保存しました')}
function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function backup(){download(`販売管理バックアップ_${today()}.json`,JSON.stringify(db,null,2),'application/json')}
function restore(file){if(!file)return;let fr=new FileReader();fr.onload=()=>{try{let x=JSON.parse(fr.result);if(!x.documents||!x.customers)throw 0;if(confirm('現在のデータをバックアップ内容に置き換えますか？')){db=x;save();render();toast('復元しました')}}catch{alert('正しいバックアップファイルではありません')}};fr.readAsText(file)}
init();
